# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=10000)),
                ('arttitle', models.CharField(max_length=100)),
                ('artkeyword', models.CharField(max_length=50)),
                ('artcontent', models.TextField()),
                ('artcreatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('artlastedittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('artread', models.IntegerField(default=0)),
                ('artcom', models.IntegerField(default=0)),
                ('artabstract', models.TextField(default='123')),
                ('classify', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default='10000')),
                ('artid', models.IntegerField(default='0')),
                ('commenttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentcontent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default='10000')),
                ('artid', models.IntegerField(default='0')),
                ('commenttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentcontent', models.TextField()),
                ('replyfirst', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default='10000')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=30)),
                ('createIP', models.CharField(max_length=16)),
                ('lastloginIP', models.CharField(max_length=16)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastlogintime', models.DateTimeField(default=django.utils.timezone.now)),
                ('userlogo', models.ImageField(default='img_upload/123_QhgxiJJ.png', upload_to='img_upload')),
                ('intr', models.CharField(default='\u5927\u5bb6\u4e00\u8d77\u52a0\u6cb9\uff01', max_length=70)),
            ],
        ),
    ]
