# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('createIP', models.CharField(max_length=15)),
                ('lastloginIP', models.CharField(max_length=15)),
                ('createtime', models.CharField(max_length=20)),
                ('lastlogin', models.CharField(max_length=20)),
                ('userlogo', models.ImageField(upload_to=b'')),
                ('confirmemail', models.BooleanField(default=False)),
                ('gold', models.IntegerField(default=10)),
                ('allpaid', models.IntegerField(default=0)),
            ],
        ),
    ]
