# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='allpaid',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='confirmemail',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='lastlogin',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='tel',
        ),
        migrations.AddField(
            model_name='userform',
            name='lastlogintime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userform',
            name='userid',
            field=models.CharField(default='m_10000', max_length=10),
        ),
        migrations.AlterField(
            model_name='userform',
            name='createIP',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='userform',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userform',
            name='lastloginIP',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
