# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20170322_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='userlogo',
            field=models.ImageField(default='img_upload/123_QhgxiJJ.png', upload_to='img_upload'),
        ),
    ]
