# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20170323_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='userid',
            field=models.IntegerField(default='10000'),
        ),
    ]
