# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20170323_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default='10000')),
                ('arttitle', models.CharField(max_length=100)),
                ('artkeyword', models.CharField(max_length=50)),
                ('artcontent', models.TextField()),
                ('artcreatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('artlastedittime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
