# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_auto_20170324_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleform',
            name='artabstract',
            field=models.TextField(default='123'),
        ),
    ]
