# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_articleform_artabstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgUploadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artid', models.IntegerField()),
                ('img', models.ImageField(upload_to='img_upload')),
                ('uploadtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
