# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_imguploadform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imguploadform',
            name='artid',
        ),
    ]
