# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_remove_imguploadform_artid'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleform',
            name='classify',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='articleform',
            name='artcom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articleform',
            name='artread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articleform',
            name='userid',
            field=models.IntegerField(default=10000),
        ),
    ]
